### ISSUE TITLE
The latest version has problems with tree growth and high memory usage（最新版本树木生长存在问题，以及内存占用过高）

### ISSUE THREAD

**Issue by buildin1** [Era4FunMC/DirtyMolia#1]
最新版本dirtymolia会导致树木生长异常，通常只会长出2格木头，无法像原版一样长在树叶里，以及我发现dirtymolia存在内存异常的问题，内存占用过高无法释放最终导致进程崩溃。经过测试他会在一下午的时间在在线人数只有20人的情况下吃掉我28GB内存最终导致服务器进程崩溃

**Comment by MrHua269** [comment]
已在 46d0fb2884ee33663c1f1eb267c89e834c2187b1 修复
