### ISSUE TITLE
Reboot does not account for users if auto save did not run prior to location + inventory (and other) changes

### ISSUE THREAD

**Issue by R00tB33rMan** [Era4FunMC/DirtyMolia#3]
"Fix": Set the auto save to a really low value like 1.

Steps to reproduce:
1: Add items to your inventory
2: Change locations
3: Ensure auto save is default and reboot when the server has been online for a decent amount of time

**Comment by MrHua269** [comment]
Try 83cdc5e4329445d5b40ea955f7335d63db6d70af

**Comment by R00tB33rMan** [comment]
Pushed build. I'll see if this is sorted as soon as I'm on

**Comment by R00tB33rMan** [comment]
Issue is resolved. Thank you for acting so quickly!
